# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 3.5
    - python: 3.6
    - python: 3.7
    - python: pypy3.5
      dist: xenial
      sudo: true

#python:
#  - "3.7"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
before_script: cd test
script:
  - py.test
